#spring.application.name=identity_service
server:
  port: 8080
  servlet:
    context-path: /identity_service
spring:
  datasource:
    #    ?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/identity_service
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5Dialect
